language: go

os:
- linux

go:
- "1.11"
- "1.10"
- "1.9"
- "1.8"

install:
- sudo apt-get install protobuf-compiler
- go get -u github.com/golang/protobuf/protoc-gen-go
- go get -d github.com/Ready-Stock/raft-badger
- make protos

